### ISSUE TITLE
How run shp2pgsql-gui-mac?

### ISSUE THREAD

**Issue by jakkry** [sembrex/shp2pgsql-gui-mac#1]
Hi! I am trying to open shp2pgsql-gui, but I can't... I need it to export shp to database. I am using macOS Mojave 10.14.6, PostgreSQL 9.6 and pgAdmin 3.  I installed Homebrew, download postgis from there (also another PostgreSQL), but I don't know what to do next... How should I run it? 

How to use it? Where? 
> Run this code from project directory
pyinstaller -w --osx-bundle-identifier=com.your.identifier --key=your-encryption-key -i pgAdmin4.icns Shp2PgsqlGUI.py

**Comment by sembrex** [comment]
`osgeo-postgis` from [homebrew-osgeo4mac](https://github.com/OSGeo/homebrew-osgeo4mac) comes with `shp2pgsql-gui`.
